// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prefectures.proto

package sample

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Prefecture struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Romaji               string   `protobuf:"bytes,3,opt,name=romaji,proto3" json:"romaji,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prefecture) Reset()         { *m = Prefecture{} }
func (m *Prefecture) String() string { return proto.CompactTextString(m) }
func (*Prefecture) ProtoMessage()    {}
func (*Prefecture) Descriptor() ([]byte, []int) {
	return fileDescriptor_prefectures_fcd1759d12cd8b1d, []int{0}
}
func (m *Prefecture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prefecture.Unmarshal(m, b)
}
func (m *Prefecture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prefecture.Marshal(b, m, deterministic)
}
func (dst *Prefecture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prefecture.Merge(dst, src)
}
func (m *Prefecture) XXX_Size() int {
	return xxx_messageInfo_Prefecture.Size(m)
}
func (m *Prefecture) XXX_DiscardUnknown() {
	xxx_messageInfo_Prefecture.DiscardUnknown(m)
}

var xxx_messageInfo_Prefecture proto.InternalMessageInfo

func (m *Prefecture) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Prefecture) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Prefecture) GetRomaji() string {
	if m != nil {
		return m.Romaji
	}
	return ""
}

type GetPrefecturesResponse struct {
	Prefectures          []*Prefecture `protobuf:"bytes,1,rep,name=prefectures,proto3" json:"prefectures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPrefecturesResponse) Reset()         { *m = GetPrefecturesResponse{} }
func (m *GetPrefecturesResponse) String() string { return proto.CompactTextString(m) }
func (*GetPrefecturesResponse) ProtoMessage()    {}
func (*GetPrefecturesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_prefectures_fcd1759d12cd8b1d, []int{1}
}
func (m *GetPrefecturesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPrefecturesResponse.Unmarshal(m, b)
}
func (m *GetPrefecturesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPrefecturesResponse.Marshal(b, m, deterministic)
}
func (dst *GetPrefecturesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPrefecturesResponse.Merge(dst, src)
}
func (m *GetPrefecturesResponse) XXX_Size() int {
	return xxx_messageInfo_GetPrefecturesResponse.Size(m)
}
func (m *GetPrefecturesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPrefecturesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPrefecturesResponse proto.InternalMessageInfo

func (m *GetPrefecturesResponse) GetPrefectures() []*Prefecture {
	if m != nil {
		return m.Prefectures
	}
	return nil
}

func init() {
	proto.RegisterType((*Prefecture)(nil), "prefectures.Prefecture")
	proto.RegisterType((*GetPrefecturesResponse)(nil), "prefectures.GetPrefecturesResponse")
}

func init() { proto.RegisterFile("prefectures.proto", fileDescriptor_prefectures_fcd1759d12cd8b1d) }

var fileDescriptor_prefectures_fcd1759d12cd8b1d = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0x4a, 0x4d,
	0x4b, 0x4d, 0x2e, 0x29, 0x2d, 0x4a, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46,
	0x12, 0x52, 0xf2, 0xe0, 0xe2, 0x0a, 0x80, 0x73, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x98, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53,
	0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x31, 0x2e, 0xb6, 0xa2, 0xfc, 0xdc,
	0xc4, 0xac, 0x4c, 0x09, 0x66, 0xb0, 0x28, 0x94, 0xa7, 0x14, 0xcc, 0x25, 0xe6, 0x9e, 0x5a, 0x82,
	0x30, 0xac, 0x38, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0xc8, 0x92, 0x0b, 0xd9, 0x4a,
	0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x71, 0x3d, 0x64, 0x97, 0x21, 0xb4, 0x05, 0x21, 0xab,
	0x75, 0xe2, 0x88, 0x62, 0x2b, 0x4e, 0xcc, 0x2d, 0xc8, 0x49, 0x4d, 0x62, 0x03, 0x3b, 0xde, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x45, 0xfb, 0x9d, 0xd1, 0x00, 0x00, 0x00,
}
